# .github/workflows/generate_json_files.yml
name: Generate JSON Translation Files from CSV

on:
  push:
    branches:
      - main # mainブランチ (または開発用ブランチ) を指定
    paths:
      - 'translations.csv' # translations.csv ファイルに変更があった時のみ実行

jobs:
  generate-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへの書き込み権限を付与

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # ワークフローがトリガーされたコミットと同じコミットを取得
          # これにより、最新の translations.csv を元に処理が行える
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # プロジェクトで使用しているNode.jsバージョン

      - name: Install dependencies
        run: npm install # package-lock.json に基づいて依存関係をインストール

      - name: Generate JSON files from CSV
        run: npm run convert-translations # package.json に定義されたコマンドを実行

      - name: Commit and push JSON files if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # src/locales ディレクトリ内の変更をステージング
          git add src/locales/*.json
          # 変更があった場合のみコミットし、なければ何もしない
          if ! git diff --staged --quiet; then
            git commit -m "Chore: Auto-generate JSON translation files from CSV"
            git push
          else
            echo "No changes to JSON translation files."
          fi
